config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  root 'homes#index'
  get 'search', to:'homes#search'
    
  get '/users', to: 'users#index'

  get 'users/profile'
  patch 'users/profile', to: 'users#update'

  get 'users/account'
  
  get 'users/rooms', to: 'users#show', as: 'users_show'

  get 'rooms/new'
  post 'rooms/new', to: 'rooms#create'

  get 'rooms/:id', to: 'rooms#show', as: 'room'
  post 'rooms/:id', to: 'reservations#confirm'

  get 'reservations/index'
  get '/reservations', to:'reservations#index'

  get 'reservations/:id', to: 'reservations#show', as: 'reservations_show'
  post 'reservations/:id', to: 'reservations#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :rooms

  has_one_attached :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: {maximum: 50}
  validates :about, length: { maximum: 200 } 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:profile, :update, :account]

  def index
    @msg = 'this is sample page.'
    @rooms = Room.all
  end

  def profile
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = "更新しました。"
      redirect_to action: :profile
    else
      flash[:alert] = "更新に失敗しました"
      render action: :profile
    end  
  end

  def account
    @user = current_user
  end  

  def show
    @user = current_user
    @rooms = @user.rooms
  end 

  private
  def user_params
    params.require(:user).permit(:image, :name, :about)
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container mt-3">

  <ul class="nav nav-pills mb-3">
    <li class="nav-item">
      <%= link_to "プロフィール", users_profile_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="#">アカウント</a>
    </li>
  </ul>
  
  <h2><%= current_user.name %>のアカウント</h2>
  <div>
    <div>
      <div>
        <div>
          <div>
            <label for="email">メールアドレス</label>
          </div>
          <p><%= @user.email %></p>
        </div>
        <div>
          <div>
            <label for="password">パスワード</label>
          </div>
          <p>*********</p>
        </div>
        <%= link_to  "編集", edit_user_registration_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>	

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/profile.html.erb
<div class="container mt-3">
  
  <ul class="nav nav-pills mb-3">
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="#">プロフィール</a>
    </li>
    <li class="nav-item">
      <%= link_to "アカウント", users_account_path, class: "nav-link" %>
    </li>
  </ul>

  <h2><%= current_user.name %>のプロフィール</h2>

  <div class="pages">
  	<div class="container align-items-center">
      <%= form_for(@user, url:{controller:'users', action:'update'}) do |form| %>
  			<div class="input_form d-flex row">
          <div class="profile-image-area d-block text-center col">
            
            <div class="user-image">
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image, class:"profile-img" %>
              <% else %> 
                <%= image_tag "default-avatar.png", class:"profile-img" %>
              <% end %>  
            </div>
            
            <div class="mt-2 align-items-center">
              <%= form.file_field :image, class:"mt-2" %>
            </div>

          </div>

          <div class="profile-text-area d-block col">
            
            <div class="row under_line">
              <div class="d-flex mb-2 align-items-center">
                <label for="name">名前</label>
                <span class="btn btn-danger btn-sm mx-2 disabled">必須</span>
              </div>
              <%= form.text_field :name, class:"form-controll" %>
            </div>
            
            <div class="mt-5">
              <div class="d-flex mb-2 align-items-center">
                <label for="image">自己紹介</label>
              </div>
              <%= form.text_area :about, class:"form-controll w-100" %>
            </div>

          </div>
        </div>	
        <div class="submit-btn m-3 d-flex justify-content-end">
          <%= form.submit "更新", class:"btn btn-primary input_submit" %>
        </div>
      <% end %>  
  	</div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <h2><%= current_user.name %>の登録したルーム</h2>
  <table class="table table-striped width">
      <thead>
        <tr>
          <th scope="col">ルーム画像</th>
          <th scope="col">ルーム名</th>
          <th scope="col">ルーム紹介</th>
          <th scope="col">料金</th>
          <th scope="col">作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= link_to room_path(room.id) do %>
                <% if room.image.attached? %>
                  <%= image_tag room.image, class:"img-thumbnail" %>
                <% else %>
                  <%= image_tag "default-room-image.png", class:"profile-img" %>
                <% end %>        
              <% end %>  
            </td>
            <td>
              <%= link_to room_path(room.id) do %>
                <p><%= room.room_name%></p>
              <% end %>  
            </td>
            <td class="room_reservation_info">
              <p><%= room.room_about %></p>
            </td>
            <td class="room_reservation_info">
              <p>¥<%= room.price %><p>
            </td>
            <td class="room_reservation_info">
              <p><%= room.created_at.strftime("%Y-%m-%d %H:%M") %><p>
            </td>
          </tr>
        <% end %> 
      </tbody>
  </table>
</div>