config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  root 'homes#index'
  get 'search', to:'homes#search'
    
  get '/users', to: 'users#index'

  get 'users/profile'
  patch 'users/profile', to: 'users#update'

  get 'users/account'
  
  get 'users/rooms', to: 'users#show', as: 'users_show'

  get 'rooms/new'
  post 'rooms/new', to: 'rooms#create'

  get 'rooms/:id', to: 'rooms#show', as: 'room'
  post 'rooms/:id', to: 'reservations#confirm'

  get 'reservations/index'
  get '/reservations', to:'reservations#index'

  get 'reservations/:id', to: 'reservations#show', as: 'reservations_show'
  post 'reservations/:id', to: 'reservations#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></p>
    </ul>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-info">
  <form class="container-fluid justify-content-between">
    <a class="navbar-brand" href="/">RoomReserve</a>
    <!-- ログインしていない場合 -->
    <% if (!user_signed_in?) %>
      <div class="navbar-item">
        <button class="btn btn-outline-success me-2" type="button">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </button>
        <button class="btn btn-outline-secondary" type="button">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </button>
      </div>
    <!-- ログインしている場合 -->
    <% else %>
      <div class="d-inline-flex align-items-center">
        <figure class="avatar-icon pt-2">
          <div class="mx-auto">
            <% if current_user.image.attached? %>
              <%= image_tag current_user.image, class:"profile-img avatar-icon-img"  %>
            <% else %>
              <%= image_tag "default-avatar.png", class:"profile-img avatar-icon-img" %>
            <% end %>  
          </div>
        </figure> 

        <a class="nav-link text-light px-3"></a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span><a class="nav-link text-light px-3"><%= current_user.name %></a></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "ルーム登録", rooms_new_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "登録済みルーム一覧", users_show_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "宿泊予約一覧", reservations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "設定", users_profile_path, class: "nav-link" %>
          <li class="nav-item">
            <%= link_to  "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        </ul>
      </div>
    <% end %>
  </form>
</nav>