config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }

  root 'homes#index'
  get 'search', to:'homes#search'
    
  get '/users', to: 'users#index'

  get 'users/profile'
  patch 'users/profile', to: 'users#update'

  get 'users/account'
  
  get 'users/rooms', to: 'users#show', as: 'users_show'

  get 'rooms/new'
  post 'rooms/new', to: 'rooms#create'

  get 'rooms/:id', to: 'rooms#show', as: 'room'
  post 'rooms/:id', to: 'reservations#confirm'

  get 'reservations/index'
  get '/reservations', to:'reservations#index'

  get 'reservations/:id', to: 'reservations#show', as: 'reservations_show'
  post 'reservations/:id', to: 'reservations#create'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

  def search
    @results = @q.result
  end

  private
    def set_q
      @q = Room.ransack(params[:q])
    end

end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<div class="top mb-5 d-flex justify-content-center">
  <div class="top-main mb-5 d-flex justify-content-center">
    <div class="container mb-5 d-flex justify-content-center align-items-center">
      <div class="search-form d-flex row justify-content-center">
        <h1 class="first-view-title">最高の旅行体験をRoomReserveで。</h1>
        <%= search_form_for @q, class:"top-search", url: search_path do |f| %>
          <%= f.search_field :adress_cont, placeholder:"東京" %>
          <%= f.submit '探す',class:"btn btn-primary" %>
        <% end %> 
      </div>
    </div>
  </div>
</div>

<div class="container recommend">
  <h3>おすすめのエリア</h3>
  <div class="row align-items-center">
    
    <div class="col"> <!-- 検索結果：東京 -->
      <%= link_to "東京", "http://[::1]:3000/search?q%5Badress_cont%5D=%E6%9D%B1%E4%BA%AC&commit=%E6%8E%A2%E3%81%99" %>
    </div>
    
    <div class="col"><!-- 検索結果：大阪 -->
      <%= link_to "大阪", "http://[::1]:3000/search?q%5Badress_cont%5D=%E5%A4%A7%E9%98%AA&commit=%E6%8E%A2%E3%81%99" %>
    </div>
    
    <div class="col"><!-- 検索結果：京都 -->
      <%= link_to "京都", "http://[::1]:3000/search?q%5Badress_cont%5D=%E4%BA%AC%E9%83%BD&commit=%E6%8E%A2%E3%81%99" %>
    </div>
    
    <div class="col"><!-- 検索結果：札幌 -->
      <%= link_to "札幌", "http://[::1]:3000/search?q%5Badress_cont%5D=%E6%9C%AD%E5%B9%8C&commit=%E6%8E%A2%E3%81%99" %>
    </div>
  </div>
</div>

app/views/homes/search.html.erb
<div class="container pages">
  <h2>検索結果：<%= @results.count %>件</h2>
  <div class="row align-items-center search">
    <% @results.each do |room| %>
      <%= link_to room_path(room) do %>

        <ul class="room-list">
          <li class="room col">
            <div class="d-flex justify-content-start">
              <div class="w-50">
                <% if room.image.attached? %>
                  <%= image_tag room.image, class:"room-imgs w-100" %>
                <% else %>
                  <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg" %>
                <% end %>
              </div>

              <div class="w-50">
                <p class="room-name">
                  <%= room.room_name %>
                </p>

                <p class="room-address">
                  <%= room.adress %>
                </p>

                <p class="room-content">
                  <%= room.room_about %>
                </p>

                <div class="room-footer">
                  <p class="room-price">
                    ¥<%= room.price %>
                  </p>
                </div>
              </div>
              </div>
          </li>
        </ul>
      <% end %>  
    <% end %>  

  </div>    
</div>